# Generated by Django 4.1 on 2024-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("task_status", models.BooleanField(default=False)),
                ("tags", models.ManyToManyField(related_name="tags", to="todo.tag")),
            ],
            options={
                "ordering": ["-create_date", "-task_status"],
            },
        ),
    ]
